### ISSUE TITLE
StructureMap.DNX problem MVC.Route

### ISSUE THREAD

**Issue by pMonfared** [structuremap/StructureMap.Microsoft.DependencyInjection#11]
StructureMap.Building.StructuremapBuildException

Error Desc

```
Error while building type Microsoft.AspNetCore.Routing.DefaultInlineConstraintResolver.  See the inner exception for details
1.) new DefaultInlineConstraintResolver(*Default of IOptions<RouteOptions>*)
2.) Microsoft.AspNetCore.Routing.DefaultInlineConstraintResolver
3.) Instance of Microsoft.AspNetCore.Routing.IInlineConstraintResolver (Microsoft.AspNetCore.Routing.DefaultInlineConstraintResolver)
4.) Container.GetInstance(Microsoft.AspNetCore.Routing.IInlineConstraintResolver)
```

Code :

```csharp
public class Startup
    {
        
        public IConfigurationRoot Configuration { set; get; }

        public Startup(IHostingEnvironment env)
        {
            var builder = new ConfigurationBuilder()
                            .SetBasePath(env.ContentRootPath)
                            .AddInMemoryCollection(new[]
                                {
                                    new KeyValuePair<string,string>("the-key", "the-value"),
                                })
                            .AddJsonFile("appsettings.json", reloadOnChange: true, optional: false)
                            .AddJsonFile($"appsettings.{env}.json", optional: true)
                            .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true)
                            .AddEnvironmentVariables();
            Configuration = builder.Build();
        }
        public IServiceProvider ConfigureServices(IServiceCollection services)
        {
            services.Configure<SmtpConfig>(options => Configuration.GetSection("Smtp").Bind(options));
            services.AddDirectoryBrowser();
            services.AddMvc();

            return IocConfig(services);
        }

        private IServiceProvider IocConfig(IServiceCollection services)
        {
            var container = new Container();
            container.Configure(config =>
            {
                config.For<IConfigurationRoot>().Singleton().Use(() => Configuration);
                config.Scan(_ =>
                {
                    _.AssemblyContainingType<IMessagesService>();
                    _.WithDefaultConventions();
                });
                //config.For<IMessagesService>().Use<MessagesService>();

                config.Populate(services);
            });
            container.Populate(services);
            return container.GetInstance<IServiceProvider>();
        }


        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory,IMessagesService messagesService)
        {

            

            loggerFactory.AddConsole();

            if (env.IsDevelopment())
            {
                app.UseStatusCodePages();
                app.UseDeveloperExceptionPage();
                //app.UseDatabaseErrorPage();
                //app.UseBrowserLink();
            }
            else
            {
                app.UseStatusCodePagesWithReExecute("/MyControllerName/SomeActionMethodName/{0}");
                app.UseExceptionHandler(errorHandlingPath: "/MyControllerName/SomeActionMethodName");
            }


            app.UseDefaultFiles();
            app.UseStaticFiles();
            app.UseFileServer();

            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });

            app.Run(async (context) =>
            {
                var siteName = messagesService.GetSiteName2();
                await context.Response.WriteAsync($"Kingdom {siteName}");
            });
        }
    }
```

**Comment by khellang** [comment]
Hmm. Not really sure why you're seeing this. It seems like SM either doesn't have the `IOptions` mechanism figured out (no call to `AddOptions` being made) or that the routing options hasn't been configured. I'll have to take a deeper look at this. Also, you're calling populate twice. That's unnecessary.

**Comment by pMonfared** [comment]
I remove one of populate, but don't fix that problem,
and i remove IOptions Mechanism but don't fix,
that is working properly with Asp.net Core DI
i upload my solution and send link here
please check it

[Download Solution from Dropbox](https://www.dropbox.com/s/35ei1gr8mn9a624/SampleFive.zip?dl=0)

**Comment by khellang** [comment]
When I look at the stack trace in #12, it looks like this is something unrelated to StructureMap. It looks like an exception is thrown in the `DefaultInlineConstraintResolver` constructor.

**Comment by khellang** [comment]
@rynowak Do you have a second to look at this?

An exception is thrown in `DefaultInlineConstraintResolver`. Specifically, when it tries to create the `RouteOptions` object:

```
System.ArgumentException: An item with the same key has already been added. Key: exists
   at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException(Object key)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Microsoft.Extensions.Options.OptionsCache`1.CreateOptions()
   at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)
   at Microsoft.Extensions.Options.OptionsCache`1.get_Value()
   at Microsoft.AspNetCore.Routing.DefaultInlineConstraintResolver..ctor(IOptions`1 routeOptions)
   at lambda_method(Closure , IBuildSession , IContext )
   --- End of inner exception stack trace ---
   at lambda_method(Closure , IBuildSession , IContext )
   at StructureMap.Building.BuildPlan.Build(IBuildSession session, IContext context) in C:\BuildAgent\work\a395dbde6b793293\src\StructureMap.Shared\Building\BuildPlan.cs:line 152
   at StructureMap.BuildSession.BuildUnique(Type pluginType, Instance instance) in C:\BuildAgent\work\a395dbde6b793293\src\StructureMap.Shared\BuildSession.cs:line 120
   at StructureMap.SessionCache.GetDefault(Type pluginType, IPipelineGraph pipelineGraph) in C:\BuildAgent\work\a395dbde6b793293\src\StructureMap.Shared\SessionCache.cs:line 68
   at StructureMap.Container.GetInstance(Type pluginType) in C:\BuildAgent\work\a395dbde6b793293\src\StructureMap.Shared\Container.cs:line 721
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.GetTreeRouter()
   at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.RouteAsync(RouteContext context)
   at Microsoft.AspNetCore.Routing.RouteCollection.<RouteAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
```

It's weird, because I can't see anything being added with the key `exists`... https://github.com/aspnet/Routing/blob/dev/src/Microsoft.AspNetCore.Routing/RouteOptions.cs#L43-L70

**Comment by khellang** [comment]
Ah, I found it! https://github.com/aspnet/Mvc/blob/a78f77afde003c4a3fcf5dd7b6dc13dd9c85f825/src/Microsoft.AspNetCore.Mvc.Core/Internal/MvcCoreRouteOptionsSetup.cs#L26

I think this might be related to the double `Populate` call; when configuring the `RouteOptions`, it probably resolves an `IEnumerable<IConfigureOptions<RouteOptions>>`, which will then have multiple instances of `MvcCoreRouteOptionsSetup`.

There's several issues here:

1. `MvcCoreRouteOptionsSetup` should check if the key already exists before adding to the dictionary.
2. StructureMap.Microsoft.DependencyInjection should check if the container has already been populated so you don't encounter this again.

**Comment by khellang** [comment]
@pMonfared Are you sure you successfully removed the second `Populate` call? I can easily reproduce it with two `Populate` calls, but not with one.

**Comment by pMonfared** [comment]
@khellang : my friend, i do Update 'project.json' to "StructureMap.Microsoft.DependencyInjection": "1.0.0"
I get error with two `Populate` 
but when use :
`private IServiceProvider IocConfig(IServiceCollection services)
        {
            var container = new Container();
            container.Configure(config =>
            {
                config.For<IConfigurationRoot>().Singleton().Use(() => Configuration);
                config.Scan(_ =>
                {
                    _.AssemblyContainingType<IMessagesSampleService>();
                    _.WithDefaultConventions();
                });
                config.For<IEmailSender>().Use<AuthMessageSender>();
                config.For<ISmsSender>().Use<AuthMessageSender>();

                //config.Populate(services);
            });

            container.Populate(services);

            return container.GetInstance<IServiceProvider>();
        }`
The problem was solved and works properly ,Thank you very much my friend

**Comment by khellang** [comment]
I've pushed a new version, v1.0.1, that prevents multiple calls to `Populate` on the same container. I've also added a remark to the XML docs on the methods.
